### ISSUE TITLE
format of the json file

### ISSUE THREAD

**Issue by mmatteo** [legend-exp/legend-dataflow-testenv#1]
Hi @oschulz,
I ended up changing a bit the structure of the json and of the file system. Please have  a look and let me know what you think about it: 
https://github.com/legend-exp/legend-dataflow-testenv/blob/e19926aa0d70080722224169d4adc87065e21604/bin/testenv-init.sh#L68

**Comment by oschulz** [comment]
I like having `"software"` in there, but we will probably still need language-specific directories. How about

```
{
  "setups": {
    "testenv": {
      "software": {
        "src": {
          "python": "$_/src/python" 
        }
        "inst": {
          "python": "$_/inst/python" 
        }
      },
      "data": {
        "raw":  "./../../TESTENV_REFPROD_BASENAME/master/data/raw",
        "gen":  "./data/gen",
        "meta": "./data/meta"
      }
    }
  }
} 
```
