### ISSUE TITLE
hard-coded path to L60 data directory in config.json file key

### ISSUE THREAD

**Issue by dcschaper** [legend-exp/legend-dataflow-testenv#10]
https://github.com/legend-exp/legend-prodenv/blob/d2dfc0abd98392cff80695607eb91e139d4d6fab/bin/prodenv-init-cycle#L48

The "orig" key in the config.json template that is created when the prodenv-init-cycle script is run is hard-coded to point to the L60 data on LNGS (even though the key it is under is called "l200"), which of course raises an issue if someone is trying to process data that is not L60. This is something that, at present, a user must manually change to point to the directory of data that they want to analyze.

**Comment by ggmarshall** [comment]
This is now cloned from the workflow template so closing
